plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "C:\\Users\\lxy_l\\.gemini\\antigravity\\brain\\53628dd3-2de3-41ab-a725-cefbc6fbfe61\\.tempmediaStorage\\dist"
publishOrigin = "ui"
commandOrigin = "ui"
command = "npm run build"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]